#!/bin/bash

docker run \
  --rm \
  -it \
  -e USER=$USER \
  -e REPO=$REPO \
  -e TOKEN=$TOKEN \
  -e DOCKERUSER=$DOCKERUSER \
  -e REGISTRY=$REGISTRY \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $PWD/builder:/builder \
  -v $PWD/repos:/repos \
  -v /home/ubuntu/.docker:/root/.docker \
  firstandthird/builder
