#!/bin/bash

docker run \
  --rm \
  -it \
  -e USER=$USER \
  -e REPO=$REPO \
  -e TOKEN=$TOKEN \
  -e REGISTRY_IMAGE=$REGISTRY_IMAGE \
  -e REGISTRY=$REGISTRY \
  -e DEBUG=$DEBUG \
  -e PUSH=$PUSH \
  -e TAG_LATEST=$TAG_LATEST \
  -e TAG_BRANCH=$TAG_BRANCH \
  -e DOCKER_AUTH=$DOCKER_AUTH \
  -e WEBHOOK=$WEBHOOK \
  -e SLACK_HOOK=$SLACK_HOOK \
  -e SLACK_CHANNEL=$SLACK_CHANNEL \
  -e TAG=$TAG \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $PWD/builder:/builder \
  -v $PWD/repos:/repos \
  firstandthird/builder
