#!/bin/bash

docker run \
  --rm \
  -it \
  -e USER=$USER \
  -e REPO=$REPO \
  -e TOKEN=$TOKEN \
  -e REGISTRY_IMAGE=$REGISTRY_IMAGE \
  -e REGISTRY=$REGISTRY \
  -e DEBUG=$DEBUG \
  -e PUSH=$PUSH \
  -e PUSH_LATEST=$PUSH_LATEST \
  -e DOCKER_AUTH=$DOCKER_AUTH \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $PWD/builder:/builder \
  -v $PWD/repos:/repos \
  firstandthird/builder
